name = "OnlinePPCACompositional"
uuid = "853432d7-57fb-4b59-8104-0bb25a65b7cc"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
